manifest:
  remotes:
    - name: zmk
      url-base: https://github.com/KamronSmith
  projects:
    - name: zmk
      remote: devel-adaptive
      revision: main
      import: app/west.yml
  self:
    path: config
